### ISSUE TITLE
No way to specify column compression 

### ISSUE THREAD

**Issue by ctweney** [databricks/spark-redshift#164]
I'm loading data in batches, and the first batch for a given table is when Redshift runs its "analyze compression" task to automagically assign compression encodings for the incoming data. However, since the data's in chunks, the first chunk of data is not representative of the variance of the whole, and Redshift chose some inappropriate encodings. 

Per the Redshift docs at http://docs.aws.amazon.com/redshift/latest/dg/t_Compressing_data_on_disk.html you can only specify encoding when a column is created (or added to an existing table). I've hunted around and can't find a way to specify encoding either as options to the COPY command or as a piece of extra baggage on the Spark-SQL-generated CREATE TABLE command. 

Is there a way to do this that I'm not seeing?

**Comment by JoshRosen** [comment]
Nope, you're not overlooking anything: as of now, there's not a mechanism to specify column compression options. If we were to add this, I imagine that the most consistent way (w.r.t the current configuration mechanisms) would be to expose this through column metadata, similar to https://github.com/databricks/spark-redshift/issues/29. However, Spark's user-facing column metadata APIs are kind of limited, hamstringing the usefulness of this when used outside of the Scala API: https://github.com/databricks/spark-redshift/issues/137.
