### ISSUE TITLE
How about adding `preactions` option?

### ISSUE THREAD

**Issue by sungjuly** [databricks/spark-redshift#167]
Recently I'm writing some code with `spark-redshift` module. And sometimes I need to clean up data before loading data into Redshift like this. How about adding `preactions` option? If you don't mind, I can contribute this. What do you think?

```
DELETE {table} WHERE {date} = value; <- This query is passed by preactions options from dataframe
COPY .......
```

BTW. I'm very thank you for making awesome libs.

**Comment by JoshRosen** [comment]
Given that we already have `postactions`, this might be reasonable. One question, though: how should this interact with database transactions? Should the pre-action be considered part of the same transaction that performs the append?

**Comment by sungjuly** [comment]
@JoshRosen Yes, I think the pre-action should be run as same transaction with copy command. Is it make sense?

**Comment by JoshRosen** [comment]
Head's up: my review bandwidth here is a bit limited, so I'm not going to be able to review this patch quickly. It's fine if you want to submit a patch as long as you don't expect it to be reviewed / merged quickly.

**Comment by sungjuly** [comment]
Cool, I will send a PR soon.
