### ISSUE TITLE
does it support to specify partition column and numbers?

### ISSUE THREAD

**Issue by biolearning** [databricks/spark-redshift#170]
Like  native Spark SQL JDBC to support partition based on specified column?

> jdbc(url, table, column=None, lowerBound=None, upperBound=None, numPartitions=None, predicates=None, properties=None)
Construct a DataFrame representing the database table accessible via JDBC URL url named table and connection properties.

The column parameter could be used to partition the table, then it will be retrieved in parallel based on the parameters passed to this function.

The predicates parameter gives a list expressions suitable for inclusion in WHERE clauses; each one defines one partition of the DataFrame.

::Note: Don’t create too many partitions in parallel on a large cluster; otherwise Spark might crash your external database systems.

Parameters:	
url – a JDBC URL
table – name of table
column – the column used to partition
lowerBound – the lower bound of partition column
upperBound – the upper bound of the partition column
numPartitions – the number of partitions
predicates – a list of expressions
properties – JDBC database connection arguments, a list of arbitrary string tag/value. Normally at least a “user” and “password” property should be included.
Returns:	
a DataFrame
New in version 1.4.

**Comment by JoshRosen** [comment]
No; if it's not documented in the README, we don't support it yet.
