### ISSUE TITLE
The false error 'The S3 bucket does not exist'

### ISSUE THREAD

**Issue by biolearning** [databricks/spark-redshift#171]
It errored as below, but actually it was observed some temporary files created on the specified S3 bucket and data was populated into Redshift. So the question is what does the error mean and why it arose?
> 16/02/04 08:23:49 ERROR Utils$: The S3 bucket lwang-bucket does not exist

> 16/02/04 08:24:08 INFO FileOutputCommitter: Saved output of task 'attempt_201602040824_0005_m_000003_0' to s3n://lwang-bucket/profiling_temp/b1ae2bab-ab51-436e-a383-26cd0a962925/_temporary/0/task_2016
02040824_0005_m_000003
16/02/04 08:24:09 INFO FileOutputCommitter: Saved output of task 'attempt_201602040824_0005_m_000001_0' to s3n://lwang-bucket/profiling_temp/b1ae2bab-ab51-436e-a383-26cd0a962925/_temporary/0/task_2016
02040824_0005_m_000001

**Comment by JoshRosen** [comment]
I believe that this is a false-positive; I'm fixing this in #177.

**Comment by biolearning** [comment]
Thanks for the quick fix. When is it going to have a new release with this fix? Or is there a way to have an early private release?

**Comment by JoshRosen** [comment]
Optimistically I'd like to do a release "soon." In the meantime, though, you can publish a custom version yourself using SBT.
