### ISSUE TITLE
Set column description from metadata

### ISSUE THREAD

**Issue by emlyn** [databricks/spark-redshift#172]
Redshift allows columns to have a comment attached (using the `COMMENT` command) that will show up in query tools.
It would be nice if we could set some metadata (e.g. "comment" or "description") on columns and have spark-redshift issue the necessary `COMMENT` commands to set them.
@JoshRosen if you think it would be useful we could do this and send a PR. While there we might also be able to look into #164.

**Comment by JoshRosen** [comment]
This sounds good to me; feel free to submit a PR. I've talked to @marmbrus and I think that column metadata is definitely the right approach here (making this API nicer in Python will happen in Spark 2.0 or later, but will happen eventually, so no need to work around the current poor Python support here).

**Comment by JoshRosen** [comment]
Fixed by #172.
