### ISSUE TITLE
Unable to read Redshift data through Spark

### ISSUE THREAD

**Issue by bigdataanalyst1** [databricks/spark-redshift#174]
I download and run these jars also placed /usr/share/aws 
> spark-shell --driver-class-path  spark-redshift_2.10-0.6.0.jar  --jars aws-java-sdk-1.10.50.jar,RedshiftJDBC41-1.1.10.1010.jar --packages com.databricks:spark-redshift_2.10:0.6.0

**Run this command to get redshift data.**
val df =sqlContext.read.format("com.databricks.spark.redshift").option("url", "jdbc:redshift://path-to.redshift.amazonaws.com:5439/mydatabase?user=myusername&password=Mypassword123").option("dbtable","users").option("tempdir", "s3://gcm/TESTING/REDSHIFT").load()
**Dataframe not created and I got this error**
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.amazon.ws.emr.hadoop.fs.EmrFileSystem not found

**I run this command instead of s3 path used local tempdir**
val df =sqlContext.read.format("com.databricks.spark.redshift").option("url", "jdbc:redshift://path-to.redshift.amazonaws.com:5439/mydatabase?user=myusername&password=Mypassword123").option("dbtable","users").option("tempdir", "/tmp/TESTING/REDSHIFT").load()
**Dataframe created, temptable also created, but If i run df.show() or select * from table I got this error.**

java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials

**In redshift  EMR_EC2_DefaultRole privileges like this.**
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1455910343000",
            "Effect": "Allow",
            "Action": [
                "redshift:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
Everything fine, but not able to access and get redshift data. Please let me know feasible solution to read and store redshift data.

**Comment by JoshRosen** [comment]
Given the `ClassNotFound` errors, it's either the case that you're missing the JARs / dependencies which provide those classes _or_ that some error is taking place while initializing those classes (missing transitive dependencies).

Given this, I'm going to resolve this issue as "not a `spark-redshift` issue".

**Comment by bigdataanalyst1** [comment]
finally I find the reason reason Redshift not supporting s3 file system. I got this error.
_Exception in thread "main" java.lang.IllegalArgumentException: spark-redshift does not support the S3 Block FileSystem. Please reconfigure `tempdir` touse a s3n:// or s3a:// scheme._

The project in S3 file system, How to resolve this issue?
