### ISSUE TITLE
Redshift Doesn't support  S3 Block file system? only s3n and s3a?

### ISSUE THREAD

**Issue by bigdataanalyst1** [databricks/spark-redshift#175]
I am trying to get redshift.
val df =sqlContext.read.format("com.databricks.spark.redshift").option("url", "jdbc:redshift://path.us-east-1.redshift.amazonaws.com:5439/database?user=uname&password=pname").option("dbtable","users").option("tempdir", "s3://tmp/REDSHIFT").load()
It gets this error.

> spark-redshift does not support the S3 Block FileSystem. Please reconfigure `tempdir` touse a s3n:// or s3a:// scheme.
Where as if i configure, local file system such as option("tempdir", "/tmp/filepath") It creating dataframe. 

It means redshift doesn't support s3 block file system?

**Comment by JoshRosen** [comment]
Yep, that's right. See https://stackoverflow.com/questions/33356041/technically-what-is-the-difference-between-s3n-s3a-and-s3, #76, and #38.
