### ISSUE TITLE
Unable to Load Redshift Table In Spark

### ISSUE THREAD

**Issue by nadersalehi** [databricks/spark-redshift#185]
Hi,

I am trying to load a table in pyspark in standalone mode but the code throws the following exception:

> pyspark --packages com.databricks:spark-redshift_2.11:0.6.0 --packages com.amazonaws:aws-java-sdk-s3:1.10.58
> <snip>
> rs_host = 'redshift_host'
> rs_user = 'redshift_username'
> rs_password = 'redshift_password'
> df = sqlContext.read.format('com.databricks.spark.redshift').option('url', 'jdbc:redshift://{0}:5439/mytable?user={1}&password={2}'.format(rs_host, rs_user, rs_passwd)).option('dbtable', 'my_table').option('tempdir', 's3n://s3_location').load()
> 16/03/04 16:56:44 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> 16/03/04 16:56:44 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> 16/03/04 16:56:47 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
> 16/03/04 16:56:47 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
> 16/03/04 16:56:48 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> 16/03/04 16:56:48 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/spark/python/pyspark/sql/readwriter.py", line 139, in load
>     return self._df(self._jreader.load())
>   File "/usr/local/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
>   File "/usr/local/spark/python/pyspark/sql/utils.py", line 45, in deco
>     return f(*a, **kw)
>   File "/usr/local/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
> py4j.protocol.Py4JJavaError: An error occurred while calling o26.load.
> : java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
> 	at com.databricks.spark.redshift.Parameters$.<init>(Parameters.scala:34)
> 	at com.databricks.spark.redshift.Parameters$.<clinit>(Parameters.scala)
> 	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:48)
> 	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
> 	at py4j.Gateway.invoke(Gateway.java:259)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:209)
> 	at java.lang.Thread.run(Thread.java:745)
> 

Below is details about spark

> $ cat /usr/local/spark/RELEASE
> Spark 1.6.0 built for Hadoop 2.6.0
> Build flags: -Psparkr -Phadoop-2.6 -Phive -Phive-thriftserver -Pyarn -DzincPort=3034
> 

Any help that put me in the right direction is greatly appreciated.

Thanks,
Nader

**Comment by JoshRosen** [comment]
Which Scala version was your Spark compiled against? It looks like you're adding a dependency on the Scala 2.11 version of `spark-redshift`, so your Spark Scala version needs to match.

**Comment by nadersalehi** [comment]
Thank @JoshRosen  for getting back so quickly.

I downloaded spark the pre-built binaries from spark.apache.org which is built with Scala 2.11

**Comment by JoshRosen** [comment]
As of Spark 1.6.0 we don't publish pre-built binaries for Scala 2.11, so I don't think that you could have downloaded one. See https://spark.apache.org/downloads.html:

> Note: Scala 2.11 users should download the Spark source package and build with Scala 2.11 support.

**Comment by nadersalehi** [comment]
Oh, I misread the statement!

After switching to 2.10, I am getting a different error, which probably is because I am not including a package:

> pyspark --packages com.databricks:spark-redshift_2.10:0.6.0,com.amazonaws:aws-java-sdk-s3:1.10.58,com.amazonaws:aws-java-sdk-core:1.10.58
> <snip>
> 
> rs_host = 'redshift_host'
> rs_user = 'redshift_username'
> rs_password = 'redshift_password'
> df = sqlContext.read.format('com.databricks.spark.redshift').option('url', 'jdbc:redshift://{0}:5439/mytable?user={1}&password={2}'.format(rs_host, rs_user, rs_passwd)).option('dbtable', 'my_table').option('tempdir', 's3n://s3_location').load()
> 16/03/04 17:39:51 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> 16/03/04 17:39:51 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> 16/03/04 17:39:55 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
> 16/03/04 17:39:55 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
> 16/03/04 17:39:56 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> 16/03/04 17:39:56 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/spark/python/pyspark/sql/readwriter.py", line 139, in load
>     return self._df(self._jreader.load())
>   File "/usr/local/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
>   File "/usr/local/spark/python/pyspark/sql/utils.py", line 45, in deco
>     return f(*a, **kw)
>   File "/usr/local/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
> py4j.protocol.Py4JJavaError: An error occurred while calling o26.load.
> : java.io.IOException: No FileSystem for scheme: s3n
> 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2584)
> 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591)
> 	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
> 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
> 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
> 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
> 	at com.databricks.spark.redshift.Utils$.assertThatFileSystemIsNotS3BlockFileSystem(Utils.scala:124)
> 	at com.databricks.spark.redshift.RedshiftRelation.<init>(RedshiftRelation.scala:48)
> 	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:49)
> 	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
> 	at py4j.Gateway.invoke(Gateway.java:259)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:209)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by JoshRosen** [comment]
This seems like a dependency issue in your environment rather than a bug in `spark-redshift`, so I'm going to close this ticket as out of scope.

**Comment by nadersalehi** [comment]
Yes, thanks for the help.  I ended up solving the issue which as you said was an environment issue.
