### ISSUE TITLE
S3 to Redshift performance

### ISSUE THREAD

**Issue by camspilly** [databricks/spark-redshift#187]
Hi All,

I've noticed that it takes 2-3 minute to load around 30-40 rows. The same of course goes for loads of 1000s of rows. The boxes we use on AWS shouldn't affect this performance considering it's independent of the scala that's running.

re: @jackar

**Comment by dkoen** [comment]
![screenshot 2016-03-10 16 35 40](https://cloud.githubusercontent.com/assets/10600425/13685402/467faf2e-e6de-11e5-9b3a-7a334376cf18.png)

**Comment by ibnipun10** [comment]
It maybe because you have a lot of partitions in spark. Try repartitioning your dataframe before writing to redshift

**Comment by JoshRosen** [comment]
If you have too many partitions, I'd consider using `coalesce()` instead of `repartition()`, since `coalesce()` should be slightly more efficient in terms of shuffling / data movement.

**Comment by ibnipun10** [comment]
I myself faced this issue. Here are 2 things you can do
1) USe coalesce to partition your data.
2) The number of partition should be proportional to the number of cores in your redshift cluster. So if your redshift is a cluster with 10 nodes and 4 cores each you can make 40 partitions of your dataframe

**Comment by dkoen** [comment]
This helped a lot, actually. Thank you.
