### ISSUE TITLE
Save Modes

### ISSUE THREAD

**Issue by eliKomoona** [databricks/spark-redshift#191]
I'm saving data in append mode, and i also want the code to ignore errors coming from the redshif in a way that they won't fail my spark app
is there a way to do so?

**Comment by JoshRosen** [comment]
Can you please elaborate and explain which errors you'd like to ignore? In other words, what types of exceptions are you seeing and why can't they be adequately ignored via a `try-catch` block in your application code?

**Comment by eliKomoona** [comment]
i have a case where i save a data frame to redshift and i get an error message that one line fails due to  a variant that is longer then it's redshift definition,  obviously i will make my code handle these cases and i will validate my data, but i will also be happy if i had the option that the entire block of data will continue to load to redshift and it wont raise an error in my app

**Comment by JoshRosen** [comment]
Can you use the `extracopyoptions` option for this? See its documentation under https://github.com/databricks/spark-redshift#parameters:

> <p>A list extra options to append to the Redshift <tt>COPY</tt> command when loading data, e.g. <tt>TRUNCATECOLUMNS</tt>
or <TT>MAXERROR n</tt> (see the <a href="http://docs.aws.amazon.com/redshift/latest/dg/r_COPY.html#r_COPY-syntax-overview-optional-parameters">Redshift docs</a>
for other options).</p>
> 
> <p>Note that since these options are appended to the end of the <tt>COPY</tt> command, only options that make sense
at the end of the command can be used, but that should cover most possible use cases.</p>

**Comment by JoshRosen** [comment]
I'm going to close this for now. Please reply / re-open if you have additional questions or if `extracopyoptions` does not address your use-case.
