### ISSUE TITLE
Insert/Update in Redshift tables

### ISSUE THREAD

**Issue by gracezxl** [databricks/spark-redshift#195]
Hi authors,

Is there any way to perform insert/update/delete sql to redshift tables using your existed functions?

**Comment by JoshRosen** [comment]
Do you mean "upsert"-type operations, like modifications to existing rows or selective deletions? Right now, this library does not have upsert support and only supports bulk appends and overwrites of rows.

**Comment by gracezxl** [comment]
Yes, right. Thanks for the information.
