### ISSUE TITLE
preactions not work as expect

### ISSUE THREAD

**Issue by bchen-talend** [databricks/spark-redshift#201]
Hello, 

I tried to save data into redshift table, but use preactions to remove all the data on the exist table by the command "delete from XXX" or "truncate XXX", and set mode with append.
the result is no data be deleted.

and I found no matter the command I set, even a wrong syntax command, no exception.

is it a bug? or wrong configuration? that is my code
sqlContext.createDataFrame(rdd, Person.class).write()
                .format("com.databricks.spark.redshift")
                .option("url", "jdbc:redshift://xxx.redshift.amazonaws.com:5439/xx?user=xx&password=xx")
                .option("dbtable", abc)
                .option("tempdir", "s3n://xx/tempdir")
                .option("preactions", "truncate " + abc)
                //.option("preactions", "delete from " + abc)
                .mode(SaveMode.Append)
                .save();
Thanks in advanced.

**Comment by JoshRosen** [comment]
This is probably because we have not yet published a Maven release which incorporates the preactions patch.

**Comment by bchen-talend** [comment]
Thanks @JoshRosen, you are right,  it's my bad, I didn't check the source. You can close this issue.
Is there any plan to have a new release?

**Comment by sungjuly** [comment]
@JoshRosen Do you have any release plan?

**Comment by camspilly** [comment]
Is there a release plan?

**Comment by khaledh** [comment]
The `preactions` option is documented on the project homepage, while the installation section mentions 0.6.0 as the release to use, which is misleading for this particular option. It's been almost 6 months since the 0.6.0 release, when can we expect to get a new release that has this functionality?

**Comment by JoshRosen** [comment]
I just published a v1.0.0 release which should incorporate this patch: https://github.com/databricks/spark-redshift/releases/tag/v1.0.0
