### ISSUE TITLE
How to download dependences on hosts with no internet

### ISSUE THREAD

**Issue by gracezxl** [databricks/spark-redshift#202]
Hi,
I want to run my scripts on multi-nodes cluster, where only one nodes has internet ip and other slaves are not. The program couldn't run successfully in those slaves have no internet and the error is ' UNRESOLVED DEPENDENCIES' (databricks#spark-redshift;0.5.1, org.apache.hadoop#hadoop-aws;2.6.0).
I don't know how to download those dependencies in these slaves. Can I just copy the ones in the worker to others?

**Comment by JoshRosen** [comment]
Short answer: the same as you would add any other dependency to your cluster, either via `--jars` or the various configurations for controlling Spark's classpaths. This question isn't `spark-redshift`-specific, so please take a look at https://spark.apache.org/docs/latest/submitting-applications.html and other general Spark resources and redirect your question to the `spark-users` mailing list if you still need help.
