### ISSUE TITLE
Number of Partitions when reading from Redshift

### ISSUE THREAD

**Issue by jomach** [databricks/spark-redshift#208]
Hi Guys, 

is there a way to control how many partitions are created when reading data from Redshift ? 

For Example : 

Table on Redshift has 200GB I'm selecting 20GB I get 500 Partitions back each partition is like 50MB which is not optimal. Of course I can Repartition after that but it should be possible to do that on the fly.

**Comment by JoshRosen** [comment]
I believe that this is determined by Redshift itself. According to the [documentation for `UNLOAD`](https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html):

> By default, UNLOAD writes data in parallel to multiple files, according to the number of slices in the cluster. The default option is ON or TRUE. If PARALLEL is OFF or FALSE, UNLOAD writes to one or more data files serially, sorted absolutely according to the ORDER BY clause, if one is used. The maximum size for a data file is 6.2 GB. So, for example, if you unload 13.4 GB of data, UNLOAD creates the following three files.

If you'd like the resulting DataFrame to contain fewer partitions, I recommend using `coalesce()`, which will reduce the number of partitions in a way that avoids unnecessary shuffles (whereas `repartition`, by default, will involve a shuffle).

**Comment by jomach** [comment]
Thx for the Tipp. Yeah with repartition I mean coalesce.
