### ISSUE TITLE
Does anyone tested extraCopyOptions on Redshift

### ISSUE THREAD

**Issue by jomach** [databricks/spark-redshift#209]
Hi, 
does anyone has recently tested the option  extraCopyOptions ? On version spark-redshift_2.10 0.6.0 ?

On my tests it did not work. 
val extra_copy_options = "TRUNCATECOLUMNS EMPTYASNULL BLANKSASNULL TRIMBLANKS IGNOREBLANKLINES FILLRECORD COMPUPDATE ON STATUPDATE ON ACCEPTANYDATE TIMEFORMAT 'auto' MAXERROR 0 "
df.option("extracopyoptions",extra_copy_options)

**Comment by eladmarom** [comment]
Hi, i encountered the same problem:
.option("extracopyoptions", "MAXERROR 1000")
is not working

**Comment by awkejiang** [comment]
tried .option("extracopyoptions", "encoding UTF8"), not working either.

**Comment by JoshRosen** [comment]
This should hopefully work in the new 1.0 release, so I'm going to close this preemptively, but please re-open if this issue re-occurs with that release.
