### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by josep2** [databricks/spark-redshift#211]
This is my query:

  val mydata = sqlContext.read
    .format("com.databricks.spark.redshift")
    .option("url", "jdbc:redshift://url")
    .option("tempdir", "s3n://bucket/")
    .option("query", "select * from table LIMIT 10")
    .load()
    .show()

Using the hadoop config for authenticaiton.

I get the following error:

16/05/26 16:38:48 ERROR Utils$: The S3 bucket bucket does not exist
16/05/26 16:38:48 INFO RedshiftRelation: UNLOAD ('QUERY') TO 's3://bucket/6dddc8c3-abb3-445b-9e9a-d75331ded4c9/' WITH CREDENTIALS 'aws_access_key_id=CRED;aws_secret_access_key=SECRET ESCAPE
[error] (run-main-0) java.lang.VerifyError: class com.fasterxml.jackson.module.scala.ser.ScalaIteratorSerializer overrides final method withResolved.(Lcom/fasterxml/jackson/databind/BeanProperty;Lcom/fasterxml/jackson/databind/jsontype/TypeSerializer;Lcom/fasterxml/jackson/databind/JsonSerializer;)Lcom/fasterxml/jackson/databind/ser/std/AsArraySerializerBase;
java.lang.VerifyError: class com.fasterxml.jackson.module.scala.ser.ScalaIteratorSerializer overrides final method withResolved.(Lcom/fasterxml/jackson/databind/BeanProperty;Lcom/fasterxml/jackson/databind/jsontype/TypeSerializer;Lcom/fasterxml/jackson/databind/JsonSerializer;)Lcom/fasterxml/jackson/databind/ser/std/AsArraySerializerBase;

I look through all the open issues, not sure which one this is related to.

**Comment by JoshRosen** [comment]
This is probably a Jackson dependency conflict. I'd check whether your AWS SDK is using a version of Jackson which conflicts with Spark's own version.

**Comment by josep2** [comment]
Thanks, I'm checking on this now I'll get back to you if it isn't resolved.

**Comment by josep2** [comment]
That fixed it. Thank you! I see your helper in the docs about this issue now too.
