### ISSUE TITLE
Backslashes in load queries are not escaped

### ISSUE THREAD

**Issue by khaledh** [databricks/spark-redshift#215]
I get a syntax error when I try to perform a load using a query that contains backslashes as literals, e.g.

```
SELECT replace(mycol, '\\', '') as col FROM mytable
```

This query gets escaped by spark-redshift (within an `UNLOAD` statement) as follows:

```
SELECT replace(mycol, \'\\\', \'\') as col FROM mytable
```

Notice that only the single quotes are escaped, while both the single quotes and the backslashes need to be escaped, as per the redshift [docs](http://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html):

```
If your query contains quotes (enclosing literal values, for example),
or backslashes (\), you need to escape them in the query text ...
```

Using the example above, the escaped query should look like:
```
SELECT replace(mycol, \'\\\\\', \'\') as col FROM mytable
```

One workaround is to add extra backslashes myself to the query. Works but definitely not a long term solution.

**Comment by JoshRosen** [comment]
Yep, this is definitely a bug. About to open a PR with a fix and will CC you for review.
