### ISSUE TITLE
Encoding issue (python)

### ISSUE THREAD

**Issue by awkejiang** [databricks/spark-redshift#217]
When i use spark-redshift with pyspark to load data to redshift, i hit the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/hdp/2.4.2.0-258/spark/python/pyspark/sql/readwriter.py", line 395, in save
    self._jwrite.save()
  File "/usr/hdp/2.4.2.0-258/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/hdp/2.4.2.0-258/spark/python/pyspark/sql/utils.py", line 45, in deco
    return f(*a, **kw)
  File "/usr/hdp/2.4.2.0-258/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o253.save.
: java.sql.SQLException: 
Error (code 1220) while loading data into Redshift: "String contains invalid or unsupported UTF8 codepoints. Bad UTF8 hex sequence: ef b7 af (error 6)"
Table name: company
Column name: description
Column type: varchar(20000)

Then i use option("extracopyoptions", "ENCODING UTF8"), still the same error. Any suggestion for this would be appreciated.

**Comment by JoshRosen** [comment]
See https://docs.aws.amazon.com/redshift/latest/dg/multi-byte-character-load-errors.html for Redshift's explanation of this error message.

According to https://forums.aws.amazon.com/thread.jspa?threadID=121370:

> We support UTF-8 characters with 3 bytes or less, with the exception of the following code points:

> 0xD800 - 0xDFFF: those are reserved for surrogate encoding, and the UTF-8 encoding of them is invalid. (Corresponding byte sequences: ED A0 80 - ED BF BF)

> 0xFDD0 - 0xFDEF, 0xFFFE, and 0xFFFF: these are listed as "noncharacters" in Unicode spec, and the UTF-8 encoding of them is also invalid. (Corresponding byte sequences: EF B7 90 - EF B7 AF, EF BF BE, and EF BF BF).

It looks like you're trying to store `EF B7 AF` / ` 0xFDEF`, which appears to be in their list of unsupported code points. As a result, I think that you'll have to either replace that character in your input or use the [ACCEPTINVCHARS](https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-conversion.html#acceptinvchars) copy option to do this for you.

As I don't think this is a `spark-redshift`-specific issue, I'm going to close this issue, but please re-open if you have evidence that this is a bug in the library and not your input data / code. Thanks!

**Comment by Anshul1106** [comment]
Hello,

can you please let me know how are you passing the "ACCEPTINVCHARS" In the code.
For example my code is something like this to unload the data to Redshift

data2.write \
    .format("com.databricks.spark.redshift") \
    .option("url","jdbc:redshift://xxxxxxxxxxxxxdbtest?user=xxxx&password=xxxxxxx") \
    .option("dbtable", "my_table") \
    .option("aws_iam_role", "arn:aws:iam::xxxxxxxxxxx:role/RedshiftCustomAdmin") \
    .option("tempdir", "s3://xxxxxxx/script/") \
    .mode("ignore") \
    .save()

Thanks in advance.

**Comment by vickymca2005** [comment]
> Hello,
> 
> can you please let me know how are you passing the "ACCEPTINVCHARS" In the code.
> For example my code is something like this to unload the data to Redshift
> 
> data2.write
> .format("com.databricks.spark.redshift")
> .option("url","jdbc:redshift://xxxxxxxxxxxxxdbtest?user=xxxx&password=xxxxxxx")
> .option("dbtable", "my_table")
> .option("aws_iam_role", "arn:aws:iam::xxxxxxxxxxx:role/RedshiftCustomAdmin")
> .option("tempdir", "s3://xxxxxxx/script/")
> .mode("ignore")
> .save()
> 
> Thanks in advance.

Did you find any solution?
