### ISSUE TITLE
Analysis exception (cannot resolve column) when mapping query results into POJOs

### ISSUE THREAD

**Issue by pneudecorb** [databricks/spark-redshift#223]
I am evaluating spark-redshift and am trying to execute a query and then map the results into a pojo.  I have the basics working but there is one column that I cannot get to map correctly.  The column type is String and contains data in the form "123.55", "98453.23456".  I cannot figure out how to convert/cast the column into a value that will map to my java class.  I am now not sure what JAVA type to map to even if I could convert it correctly. I've tried seemingly everything.  

This redshift query is valid, and similar to what I specify for my query

```
select duration_in_seconds::float8 as durationSeconds from cgs.product_detail_exploration;
```

Here is my DataSet definition,

```java
Dataset<MyPojo> ds = sqlContext.read()
                .format("com.databricks.spark.redshift")
                .option("url", buildRedshiftUrl(prop))
                //.option("dbtable", "cgs.product_detail_exploration")
                .option("tempdir", prop.getProperty("aws.temp_s3_loc"))
                //.option("fetchSize", "100")
                .option("query", sql) // query is similar to one above, but with additional fields
                .load().as(Encoders.bean(MyPojo.class));
```

MyPojo is JAVA Bean compliant and has an attribute named durationSeconds that is defined as a Double.

I keep getting this error,

```
Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve 'durationSeconds' given input columns: [userid, url, systemcode, durationseconds];
```

**Comment by JoshRosen** [comment]
I think that this may be a case-sensitivity issue: by default (`spark.sql.caseSensitive`) the query analyzer is case-sensitive, so it looks like your POJO field named `durationSeconds` is not matching against the Redshift table's column named `durationseconds` (see the [documentation for `.as[]`](https://github.com/apache/spark/blob/v1.6.2/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L120)).

According to the [Redshift documentation's section on names and identifiers](https://docs.aws.amazon.com/redshift/latest/dg/r_names.html):

> Names identify database objects, including tables and columns, as well as users and passwords. The terms name and identifier can be used interchangeably. There are two types of identifiers, standard identifiers and quoted or delimited identifiers. Standard and delimited identifiers are case-insensitive and are folded to lower case. 

When we query Redshift to discover the schema of your query, I think that the resulting column name that's returned is lowercased, hence this mismatch.

You have two options to fix this:

1. Enable case-insensitivity.
2. Rename the columns: `.load().withColumnRenamed("durationseconds", "durationSeconds")`

**Comment by pneudecorb** [comment]
Thanks Josh.  I'll try enabling case-Insensitivity.  Is this done by setting the configuration key, "spark.sql.caseSensitive" on the SQLContext instance, as in,

        sqlContext.setConf("spark.sql.caseSensitive", "true");

Once I set that configuration element (assuming its correct), I now get this uninformative (to me) stack trace.  Any idea what might be generating the NullPointerException?

Note: If I remove the .load().as(Encoders.bean(...class)), the exception below goes away.

Exception in thread "main" java.lang.NullPointerException
	at org.spark-project.guava.reflect.TypeToken.method(TypeToken.java:465)
	at org.apache.spark.sql.catalyst.JavaTypeInference$$anonfun$2.apply(JavaTypeInference.scala:110)
	at org.apache.spark.sql.catalyst.JavaTypeInference$$anonfun$2.apply(JavaTypeInference.scala:109)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.sql.catalyst.JavaTypeInference$.org$apache$spark$sql$catalyst$JavaTypeInference$$inferDataType(JavaTypeInference.scala:109)
	at org.apache.spark.sql.catalyst.JavaTypeInference$.inferDataType(JavaTypeInference.scala:54)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$.javaBean(ExpressionEncoder.scala:72)
	at org.apache.spark.sql.Encoders$.bean(Encoder.scala:182)
	at org.apache.spark.sql.Encoders.bean(Encoder.scala)
...

J.D.

**Comment by pneudecorb** [comment]
Josh,

If I change all the column names to lowercase (and pojo attributes), the binding succeeds.  I guess I still need to understand how to set the configuration that disables case sensitivity.

I've tried the following:

        sqlContext.setConf("spark.sql.caseSensitive", "false");
        sqlContext.sql("set spark.sql.caseSensitive=false");

I'm assuming once I can disable case sensitivity, I'll be able to use camel cased names for my result set columns.

**Comment by JoshRosen** [comment]
It's possible that there's a bug in case-insensitive POJO encoding. It looks like the NPE that you saw is being thrown from https://github.com/apache/spark/blob/v1.6.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/JavaTypeInference.scala#L110 (assuming Spark 1.6.1, but the code is the same in 1.6.2). My hunch is that `property.getReadMethod()` is returning `null` (which it is [allowed to](https://docs.oracle.com/javase/7/docs/api/java/beans/PropertyDescriptor.html#getReadMethod())).

It would be helpful to see if this problem can be reproduced with a single-field POJO and dummy dataset, which should be possible since I think this is a Spark SQL problem and not an issue with `spark-redshift` itself, per-se.
