### ISSUE TITLE
When trying to load data into amazon redshift through spark. It is not loading in existing table instead it is creating staging table.

### ISSUE THREAD

**Issue by manisha803** [databricks/spark-redshift#224]
finalpagedata1.write.format("com.databricks.spark.redshift").option("url", jdbcURL).option("tempdir",tempS3Dir).option("dbtable","public.hits") .mode(SaveMode.Overwrite).save().

It is creating staging table with datatype text. So it will not take more than 256 character.

**Comment by manisha803** [comment]
I wanted to directly load data into the redshift table. It is creating staging table.

**Comment by eladmarom** [comment]
add .option("usestagingtable", "false")

**Comment by eladmarom** [comment]
by the way, all table string fields are of type TEXT (VARCHAR(256)), in the documentation there's a section on how to overcome the obstacle of column length.

**Comment by JoshRosen** [comment]
Yep, this is the expected behavior for `SaveMode.Overwrite` as of `spark-redshift` 0.6.0 and below; see the README for more details.

**Comment by manisha803** [comment]
Thank you so much. This does help.
