### ISSUE TITLE
How to exception handle in Spark

### ISSUE THREAD

**Issue by manisha803** [databricks/spark-redshift#225]
I am working with Spark. I am loading big file into Redshift from directory S3. If any reason data load failed. I wanted to reject bad records and load continue.
Is there any ways to do in spark

**Comment by JoshRosen** [comment]
To clarify, are you trying to insert records into an existing Redshift table and experiencing failures because Redshift is rejecting records as being incompatible with your schema / integrity constraints / character encoding / string lengths?

**Comment by manisha803** [comment]
Correct. currently, for any reason records is not being inserted then it should be rejected and load continue. Currently, load is failed.

**Comment by eladmarom** [comment]
hey, you should add:
.option("extracopyoptions", s"MAXERROR $maxErrors") to the write command,
when maxErrors should not pass 100000,
this will allow the copy command to continue until 100000 failures.

**Comment by manisha803** [comment]
How do I capture error records in different file.

**Comment by manisha803** [comment]
Go message to continue load while failure. Is there any way to capture those records.

**Comment by emlyn** [comment]
Have a look at the Redshift [`STL_LOAD_ERRORS`](http://docs.aws.amazon.com/redshift/latest/dg/r_STL_LOAD_ERRORS.html) table, maybe that gives you what you want.
