### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by marmbrus** [databricks/spark-redshift#23]
It would be good to get this back up to 90%+

**Comment by JoshRosen** [comment]
Note to self: key thing to test is Scala 2.11 for Spark 1.5, plus tests for anything that renames / works with temporary tables. Make sure that we handle error recovery, etc.

**Comment by JoshRosen** [comment]
I'm going to mark this as resolved for now. We're now at 95%+ coverage and have tests for Scala 2.11. I've manually audited the SaveMode code and think that things are fine there fore now. We may want to add tests in the future before refactoring that code, but let's do that later once we actually make those changes.
