### ISSUE TITLE
Failing to save a string to redshift

### ISSUE THREAD

**Issue by samelamin** [databricks/spark-redshift#232]
I have had difficulties saving a json to redshift because it has multiple nested parts

so I would like to save the entire json as a string in one column, but seems that redshift doesnt allow you to save things as text and just assigns VARCHAR(300) to the column type

I set the type to VARCHAR(MAX) and when although it inserts the massive string to redshift from a seperate client. When I try to save it from the connector in my spark job it just saves it as an empty string

However if I limit the number of characters then it works

I assume it might be because the staging table being created cant take the limit of characters

Also if it helps using (SaveMode.Overwrite) doesnt work because of " while loading data into Redshift: "String length exceeds DDL length""

but SaveMode.Append is the one that saves an empty string

**Comment by JoshRosen** [comment]
Two suggestions:

- Try using the just-released `spark-redshift` v1.0.0, which fundamentally changes the way that staging tables work and may fix this problem.
- Try setting the maximum length of the string column via https://github.com/databricks/spark-redshift#configuring-the-maximum-size-of-string-columns

**Comment by samelamin** [comment]
Hi @JoshRosen It seems setting the column size only works on the scala APIs, 

How will I convert the string to a dataframe? 

because at the moment I am using the below and I know that wont work right?


sqlContext.sql(s"select '$stringToSave' as Message")
            .write.format("com.databricks.spark.redshift")
            .option("url", jdbcURL)
            .option("tempdir", tempS3Dir)
            .option("dbtable", "destination_table")
            .mode(SaveMode.Overwrite)
            .save()

**Comment by samelamin** [comment]
Closing as not an issue any longer
