### ISSUE TITLE
Saving to redshift table without duplicates

### ISSUE THREAD

**Issue by samelamin** [databricks/spark-redshift#238]
Hi guys

Great support so far

So my question is, is there a way to save to a redshift table but not store duplicates? 

assuming my dataframe has data that is exactly the same as the one in the the destination redshift table

Since there is no primary key support in redshift per se, im assuming this isnt as straightforward as I hope

**Comment by BreachSim** [comment]
I don't think there is a built in mechanism for that in redshift or spark-redshift. As far as I know you need to handle that by code. 
There is 2 ways that I can think of to handle that.
1: Add another column in your redshift table, like an insert timestamp, to allow duplicate but to know wich one came first or last and then delete the duplicate afterwards if you need to.
2: Load the previously inserted data and compare the data to be insert to avoid inserting duplicates.

If there is other way to handle this im all ears!
