### ISSUE TITLE
Handle full queries as well as table names.

### ISSUE THREAD

**Issue by marmbrus** [databricks/spark-redshift#24]
We should be able to handle full queries that use things like redshift joins or aggregation.  In Spark JDBC we do this by wrapping the query in a subquery.  I propose the following interface.  If `query` is specified instead of `dbtable` lets wrap it in `()` and pass it as a subquery.

**Comment by traviscrawford** [comment]
@marmbrus - can you elaborate on how you're pushing aggregations into Redshift? While doing an aggregation on a large Redshift table my driver OOM'd, and looking in the query log and explain plan I realized loading a JDBC data frame pushes filters into Redshift, but does the aggregation in Spark.

To work around this I'm actually running JDBC queries directly, then converting that result set to a data frame for use elsewhere.

**Comment by traviscrawford** [comment]
Here's a simplified version of what we're doing. I would be very interested in Spark pushing aggregations into Redshift so we can do away with this.

```
// Simplified to illustrate the general idea.
def toDataFrame(sql: String)(implicit sc: SparkContext, sqlContext: SQLContext): DataFrame = {
    val conn = getRedshiftConn
    val st: Statement = conn.createStatement
    val rs = st.executeQuery(sql)
    val metaData = rs.getMetaData
    val rows = new Iterator[Row] {
      def hasNext = rs.next()
      def next() = {
        val cols = for (i <- 1 to metaData.getColumnCount) yield {
          metaData.getColumnType(i) match {
            case java.sql.Types.BIGINT => rs.getLong(i)
            case java.sql.Types.BOOLEAN => rs.getBoolean(i)
            case java.sql.Types.DOUBLE => rs.getDouble(i)
            case java.sql.Types.INTEGER => rs.getInt(i)
            case java.sql.Types.VARCHAR => rs.getString(i)
            case _ => throw new IllegalStateException(
              s"Unexpected SQL column type ${metaData.getColumnTypeName(i)}" +
                s" of column ${metaData.getColumnName(i)}")
          }
        }
        Row(cols: _*)
      }
    }.toBuffer

    val schema = resultSetMetaData2StructType(rs.getMetaData)
    val rdd = sc.parallelize(rows)
    sqlContext.createDataFrame(rdd, schema)
```

**Comment by marmbrus** [comment]
We don't do any automatic pushdown of aggregations (only filters and projection), and doing so is a little ways out.  Fortunately, I think you should still be able to simplify the above (and get parallel reads that don't collect to the driver).

Rough, untested sketch:
```scala
def redshift(sql: String)(implicit sqlContext: SQLContext) = 
  sqlContext.read
    .format("com.databricks.spark.redshift")
    .option("url", "jdbc:postgresql://redshifthost:5439/database?user=username&password=pass")
    .option("dbtable" -> "(" + sql + ")")
    .option("tempdir" -> "s3://path/for/temp/data")
    .load()
```

**Comment by traviscrawford** [comment]
Thanks for the info about the aggregation pushdown timeline.

I actually started with the ~code you showed above, but switched to collecting in the driver intentionally to do aggregation in Redshift since that's what makes the most sense in our current setup (Redshift DW, using Spark to to drive workflows).

**Comment by marmbrus** [comment]
That code will do aggregation in redshift as long as you express the
aggregation in the SQL string and not as subsequent operations on the
resulting dataframe.

**Comment by JoshRosen** [comment]
This essentially just needs a test case, plus maybe some syntactic sugar for the table name thing (which can be pushed to the next release if necessary).
