### ISSUE TITLE
Date Conversion from string yyyymmdd to redshift date format YYYY-MM-DD

### ISSUE THREAD

**Issue by manisha803** [databricks/spark-redshift#241]
I have source field date coming in YYYYMMDD format. When trying load on redshift it is giving error saying that few character then expected. expected format is YYYY-MM-DD format.
how to convert YYYYMMDD string TO YYYY-MM-DD date format

**Comment by JoshRosen** [comment]
Looks like this is duplicated by #242, so let's continue the discussion there instead.

**Comment by manisha803** [comment]
Thanks Josh for prompt reply. Is there any solution available.
