### ISSUE TITLE
While loading data into redshift using spark-redshift API, It is giving error for date column. 

### ISSUE THREAD

**Issue by manisha803** [databricks/spark-redshift#242]
When I am trying to load data into redshift using Spark-redshift API. Source file has column name = Date and value format is "YYYYMMDD". But when trying to load data into redshift it is giving error saying that fewer then expected character. Expected atleast 10.

**Comment by JoshRosen** [comment]
Can you provide a more specific example of what you're trying to do? Are you trying to append to an existing Redshift table containing a DATE-type column? If you run `printSchema` on the Spark DataFrame that you're trying to save, does the result show the date column as being of string type or date type?

**Comment by manisha803** [comment]
Thank you so much for your reply.

Let me describe problem:

I have source file with 300 columns. I am using Spark-Redshift API to load data into Redshift.
File has column name “date” and value coming in YYYYMMDD format.
I have created data frame using following code

val df = sqlContext.read
    .format("com.databricks.spark.csv")
    .option("header", "true")
    .option("delimiter", "~")
    .load(args(0))
I am trying to write data in redshift using following code.

df.write.format("com.databricks.spark.redshift").
    option("url", jdbcURL).option("tempdir",tempS3Dir)
    .option("dbtable",hittable).option("avrocompression", "snappy").mode("Append").save()

It is giving me error saying that
“Invalid Date Format - length must be 10 or more     “
8676939154651926876-2||2|1467651327|1467651327|20160704|8676939154651926876||1|3|3|58|||||||||||google|organic|(not provided)||||||||||||||Safari|9.0|iOS|9.3.2|false|Apple|(not set)|false|en-us|32-bit|375x667|mobile|Americas|Northern America|United States|Colorado|Denver CO|

Highlighted filed is I am passing as date column value.

Redshift table has column name = “date” and datatype = date.


Thanks
Manisha

**Comment by JoshRosen** [comment]
The problem is that you're trying to insert a string into a date column which is failing because the string isn't in the expected format. You have two options: convert the string into a Date in Spark SQL so that the resulting data frame's column has Date type, in which case `spark-redshift` will do the right thing while writing it back, or use `extracopyoptions` to specify a custom date format (see Redshift docs to see how to do this).
