### ISSUE TITLE
Dependency issues when using --packages option with spark

### ISSUE THREAD

**Issue by BreachSim** [databricks/spark-redshift#244]
I encounter an issue when using the packages option with spark shell. Any idea why is this happening?
im using spark 1.6.1 on amazon EMR emr-4.7.1

```
**spark-shell --packages com.databricks:spark-redshift_2.10:0.6.0**
Ivy Default Cache set to: /home/hadoop/.ivy2/cache
The jars for the packages stored in: /home/hadoop/.ivy2/jars
:: loading settings :: url = jar:file:/usr/lib/spark/lib/spark-assembly-1.6.1-hadoop2.7.2-amzn-2.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-redshift_2.10 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found com.databricks#spark-redshift_2.10;0.6.0 in central
	found org.slf4j#slf4j-api;1.7.5 in local-m2-cache
	found com.databricks#spark-avro_2.10;2.0.1 in central
	found org.apache.avro#avro;1.7.6 in central
	found org.codehaus.jackson#jackson-core-asl;1.9.13 in local-m2-cache
	found org.codehaus.jackson#jackson-mapper-asl;1.9.13 in local-m2-cache
	found com.thoughtworks.paranamer#paranamer;2.3 in local-m2-cache
	found org.xerial.snappy#snappy-java;1.0.5 in local-m2-cache
	found org.apache.commons#commons-compress;1.4.1 in local-m2-cache
	found org.tukaani#xz;1.0 in local-m2-cache
downloading https://repo1.maven.org/maven2/com/databricks/spark-redshift_2.10/0.6.0/spark-redshift_2.10-0.6.0.jar ...
	[SUCCESSFUL ] com.databricks#spark-redshift_2.10;0.6.0!spark-redshift_2.10.jar (27ms)
downloading https://repo1.maven.org/maven2/com/databricks/spark-avro_2.10/2.0.1/spark-avro_2.10-2.0.1.jar ...
	[SUCCESSFUL ] com.databricks#spark-avro_2.10;2.0.1!spark-avro_2.10.jar (13ms)
downloading https://repo1.maven.org/maven2/org/apache/avro/avro/1.7.6/avro-1.7.6.jar ...
	[SUCCESSFUL ] org.apache.avro#avro;1.7.6!avro.jar(bundle) (22ms)
downloading file:/home/hadoop/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar ...
	[SUCCESSFUL ] org.apache.commons#commons-compress;1.4.1!commons-compress.jar (2ms)
downloading file:/home/hadoop/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar ...
	[SUCCESSFUL ] org.tukaani#xz;1.0!xz.jar (2ms)
:: resolution report :: resolve 2496ms :: artifacts dl 88ms
	:: modules in use:
	com.databricks#spark-avro_2.10;2.0.1 from central in [default]
	com.databricks#spark-redshift_2.10;0.6.0 from central in [default]
	com.thoughtworks.paranamer#paranamer;2.3 from local-m2-cache in [default]
	org.apache.avro#avro;1.7.6 from central in [default]
	org.apache.commons#commons-compress;1.4.1 from local-m2-cache in [default]
	org.codehaus.jackson#jackson-core-asl;1.9.13 from local-m2-cache in [default]
	org.codehaus.jackson#jackson-mapper-asl;1.9.13 from local-m2-cache in [default]
	org.slf4j#slf4j-api;1.7.5 from local-m2-cache in [default]
	org.tukaani#xz;1.0 from local-m2-cache in [default]
	org.xerial.snappy#snappy-java;1.0.5 from local-m2-cache in [default]
	:: evicted modules:
	org.slf4j#slf4j-api;1.6.4 by [org.slf4j#slf4j-api;1.7.5] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   11  |   10  |   10  |   1   ||   10  |   5   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		[NOT FOUND  ] org.slf4j#slf4j-api;1.7.5!slf4j-api.jar (0ms)

	==== local-m2-cache: tried

	  file:/home/hadoop/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar

		[NOT FOUND  ] org.codehaus.jackson#jackson-core-asl;1.9.13!jackson-core-asl.jar (0ms)

	==== local-m2-cache: tried

	  file:/home/hadoop/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar

		[NOT FOUND  ] org.codehaus.jackson#jackson-mapper-asl;1.9.13!jackson-mapper-asl.jar (0ms)

	==== local-m2-cache: tried

	  file:/home/hadoop/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar

		[NOT FOUND  ] com.thoughtworks.paranamer#paranamer;2.3!paranamer.jar (0ms)

	==== local-m2-cache: tried

	  file:/home/hadoop/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar

		[NOT FOUND  ] org.xerial.snappy#snappy-java;1.0.5!snappy-java.jar(bundle) (0ms)

	==== local-m2-cache: tried

	  file:/home/hadoop/.m2/repository/org/xerial/snappy/snappy-java/1.0.5/snappy-java-1.0.5.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.slf4j#slf4j-api;1.7.5!slf4j-api.jar

		:: org.codehaus.jackson#jackson-core-asl;1.9.13!jackson-core-asl.jar

		:: org.codehaus.jackson#jackson-mapper-asl;1.9.13!jackson-mapper-asl.jar

		:: com.thoughtworks.paranamer#paranamer;2.3!paranamer.jar

		:: org.xerial.snappy#snappy-java;1.0.5!snappy-java.jar(bundle)

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: org.slf4j#slf4j-api;1.7.5!slf4j-api.jar, download failed: org.codehaus.jackson#jackson-core-asl;1.9.13!jackson-core-asl.jar, download failed: org.codehaus.jackson#jackson-mapper-asl;1.9.13!jackson-mapper-asl.jar, download failed: com.thoughtworks.paranamer#paranamer;2.3!paranamer.jar, download failed: org.xerial.snappy#snappy-java;1.0.5!snappy-java.jar(bundle)]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1068)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:287)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:154)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by JoshRosen** [comment]
Hmm, it looks like the dependencies are being downloaded from Maven but it appears that Spark is searching for them in the `/home/hadoop/.m2` Maven cache. Can you check whether they were downloaded to ` /home/hadoop/.ivy2` instead?

Also, @brkyvz, do you have any idea what might be happening here?

**Comment by BreachSim** [comment]
@JoshRosen 

Somehow this issue have been resolved. I don't know if it was AWS specific or not but now it just works.

Thanks for your support.

**Comment by BreachSim** [comment]
Reopened the issue it's not resolved.  Mistakenly closed it. sorr about that.

@JoshRosen  The jars are in the /home/hadoop/.ivy2/cache/ folder. they are not in /home/hadoop/.m2/repository/

**Comment by BreachSim** [comment]
I found that the issue is related to the fact that I installed maven on the EMR cluster prior to call spark-shell with the packages option. Without maven installed it works as expected.

**Comment by JoshRosen** [comment]
Weird. This issue doesn't sound `spark-redshift`-specific, so I'm going to close this, but feel free to raise a Spark JIRA for this issue.

**Comment by dfdeshom** [comment]
Ran into the same issue. In my case, I deleted my `$HOME/.ivy2` directory and ran `./bin/spark-shell --packages com.databricks:spark-redshift_2.10:2.0.0` again to get rid of the issue.

**Comment by ndimiduk** [comment]
I'm seeing a similar conflict with both maven and ivy available on my submit box. Was this opened as an issue someplace upstream where I can followup?

**Comment by lukewendling** [comment]
i had a similar issue with a package specified in spark-defaults.conf. I removed it and used the `--packages` option to `spark-submit` instead and haven't had the problem since.

**Comment by DerekHanqingWang** [comment]
The problem has nothing related with spark or ivy itself. It's essentially maven repo issue. When you specify a 3rd party lib in --packages, ivy will first check local ivy repo and local maven repo for the lib as well as all its dependencies. If found, it won't try to download it from central repo. However, when searching the local maven repo, ivy will only check if the directory of artifact exists without checking if there is actually jar file in the dir.

found com.thoughtworks.paranamer#paranamer;2.3 in local-m2-cache

This msg indicates that directory of paranamer-2.3.jar was found in local maven repo. But if you go to the directory, you will find no jar file there. I think it's because maven tried to download the artifact from central before but failed to get the jar for some reason.

A solution is to remove related dir in .ivy2/cache, ivy2/jars and .m2/repository/

**Comment by AydinChavez** [comment]
this issue happened to me some times also on a non-spark-redshift related project, so I guess it is a general spark issue (?)

DerekHanqingWang's workaround worked for me.

**Comment by bixingxie** [comment]
I had a similar issue and DerekHanqingWang's solution works for me perfectly.

**Comment by rajat1401** [comment]
> The problem has nothing related with spark or ivy itself. It's essentially maven repo issue. When you specify a 3rd party lib in --packages, ivy will first check local ivy repo and local maven repo for the lib as well as all its dependencies. If found, it won't try to download it from central repo. However, when searching the local maven repo, ivy will only check if the directory of artifact exists without checking if there is actually jar file in the dir.
> 
> found com.thoughtworks.paranamer#paranamer;2.3 in local-m2-cache
> 
> This msg indicates that directory of paranamer-2.3.jar was found in local maven repo. But if you go to the directory, you will find no jar file there. I think it's because maven tried to download the artifact from central before but failed to get the jar for some reason.
> 
> A solution is to remove related dir in .ivy2/cache, ivy2/jars and .m2/repository/

Any idea on how to do this repeatedly when submitting jobs on emr via livy? Because for my each job it tries to check for the package and upon not finding the directory, tries to install it from maven central and fails due to some error. @DerekHanqingWang

**Comment by roalonsor** [comment]
> The problem has nothing related with spark or ivy itself. It's essentially maven repo issue. When you specify a 3rd party lib in --packages, ivy will first check local ivy repo and local maven repo for the lib as well as all its dependencies. If found, it won't try to download it from central repo. However, when searching the local maven repo, ivy will only check if the directory of artifact exists without checking if there is actually jar file in the dir.
> 
> found com.thoughtworks.paranamer#paranamer;2.3 in local-m2-cache
> 
> This msg indicates that directory of paranamer-2.3.jar was found in local maven repo. But if you go to the directory, you will find no jar file there. I think it's because maven tried to download the artifact from central before but failed to get the jar for some reason.
> 
> A solution is to remove related dir in .ivy2/cache, ivy2/jars and .m2/repository/

I tried to apply this in Pyspark running on Kubernetes. I ran `rm -rf /opt/spark/.ivy2/jars && rm -rf /opt/spark/.ivy2/cache && rm -rf /opt/spark/.m2/repository` just after spark-submit and right before the script that do the actual dataframe processing, as shown here: 

`import findspark `
`from pyspark import SparkContext, SparkConf`
`from pyspark.sql import SparkSession`
`from pyspark.sql.types import StringType, StructType, StructField, IntegerType, TimestampType, DateType
findspark.init()`
`import subprocess`

`# Cleaning unresolved dependencies`
`cmd = "rm -rf /opt/spark/.ivy2/jars && rm -rf /opt/spark/.ivy2/cache && rm -rf /opt/spark/.m2/repository"`
`process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)`
`output, error = process.communicate()`
`if output:`
  `print(output)`
`if error:`
  `print(error)`
`... # rest of the file`

but it does not work. Where should I clean the mentioned directories?
