### ISSUE TITLE
add support for spark 2

### ISSUE THREAD

**Issue by eranmizrahi** [databricks/spark-redshift#246]
spark 2 was just released...

**Comment by JoshRosen** [comment]
Yep, I'll publish an official 2.0.0-compatible release as soon as we do a corresponding release for `spark-avro`. In the meantime, though, I believe that you should be able to use the `2.0.0-preview1` release of `spark-redshift` with the official Spark 2.0.0 release (it should be binary-compatible).

**Comment by JoshRosen** [comment]
I've just released `spark-redshift` 2.0.0 to Maven Central and Spark Packages: https://github.com/databricks/spark-redshift/releases/tag/v2.0.0
