### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by mkanchwala** [databricks/spark-redshift#25]
can we push this to maven central, just like spark-avro and spark-csv

**Comment by mkanchwala** [comment]
Also I am not able to find the dependency for 0.4.1

<repositories>
        <repository>
            <id>SparkPackagesRepo</id>
            <name>Spark Packages Repo</name>
            <url>https://dl.bintray.com/spark-packages/maven/</url>
            <layout>default</layout>
        </repository>
    </repositories>

Can you please help me here, I am using Maven.

Thanks

**Comment by marmbrus** [comment]
We'll publish to maven after the new Spark SQL support is finalized.  Sometime before the Spark 1.5 release.

**Comment by mkanchwala** [comment]
Sounds cool!

**Comment by JoshRosen** [comment]
This is done: http://central.maven.org/maven2/com/databricks/
