### ISSUE TITLE
How can I control the number of partitions of the resultant data frame without using coalesce or re-partition?

### ISSUE THREAD

**Issue by chanansh** [databricks/spark-redshift#256]
Is there a way to control the number of partitions of the the retrieved dataframe? 
Currently I get 2000 partitions where my data is very small and also the number of nodes.
I know I can change it post extraction using `repartition` or `coalesce` but this takes a lot of time.

**Comment by JoshRosen** [comment]
According to the [Redshift `UNLOAD` documentation](https://docs.aws.amazon.com/redshift/latest/dg/t_Unloading_tables.html):

> By default, UNLOAD writes data in parallel to multiple files, according to the number of slices in the cluster. To write data to a single file, specify PARALLEL OFF.

To my knowledge there is no mechanism to customize the number of partitions written by Redshift during an unload, aside from choosing between parallel and non-parallel unloads.

As is mentioned at the start of the README, the `spark-redshift` library is more optimized towards bulk operations which work with large numbers of rows and will not be very efficient for high-selectivity, low-latency interactive queries. Thus, depending on your use-case it may make more sense to use Spark's `jdbc` data source if you're working with a relatively small amount of data.

Are you winding up with many _empty_ partitions in your unloaded dataset or is the number of rows per partition too low? If it's the former, then it's possible that `spark-redshift` could take steps to skip those empty partitions when constructing the DataFrame from the unloaded files.
