### ISSUE TITLE
spark-redshift should support JDBC42

### ISSUE THREAD

**Issue by traviscrawford** [databricks/spark-redshift#258]
Per http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html the latest Redshift driver is `RedshiftJDBC42-1.1.17.1017.jar`

When using JDBC42 the driver class name is `com.amazon.redshift.jdbc42.Driver`

```
$ unzip ~/Desktop/RedshiftJDBC42-1.1.17.1017.jar META-INF/services/java.sql.Driver
Archive:  /Users/traviscrawford/Desktop/RedshiftJDBC42-1.1.17.1017.jar
 extracting: META-INF/services/java.sql.Driver  
$ cat META-INF/services/java.sql.Driver 
com.amazon.redshift.jdbc42.Driver
```

[RedshiftJDBCWrapper.getDriverClass](https://github.com/databricks/spark-redshift/blob/master/src/main/scala/com/databricks/spark/redshift/RedshiftJDBCWrapper.scala) should be updated to support JDBC 4.2.

**Comment by JoshRosen** [comment]
+1. This was on my own mental backlog of things to fix but I guess I forgot to file a ticket. If you've got time, want to submit a PR to fix this? Should be easy and I'll review right away, then can push a point release once it's merged.

**Comment by traviscrawford** [comment]
Sure thing - will send a PR in a sec.

**Comment by traviscrawford** [comment]
No rush on publishing this, btw. Folks can make progress with the current release with:

```
.option("jdbcdriver", "com.amazon.redshift.jdbc42.Driver")
```

**Comment by JoshRosen** [comment]
Yeah, there's definitely a workaround but I'm worried about the impact on out-of-the-box behavior for new users who may choose to download the 4.2 version of the driver because it's the newest.
