### ISSUE TITLE
Colum Encoding in Redshift with Metadata

### ISSUE THREAD

**Issue by haisano** [databricks/spark-redshift#262]
Hi,

I am trying to add the column encoding for Redshift table using the encoding metadata. But, I am not able to get it correct. May I know if there is something that I miss?

    myDF = // the data frame that has the fields. 

    val columnsEncodeMap = Map(
      "activation_date"  ->  "delta",
      "acceptance_date"  ->  "delta"
    )

    columnsEncodeMap.foreach { case (colName, encodeType) =>
      val metadata = new MetadataBuilder().putString("encoding", encodeType).build()
      myDF = myDF.withColumn(colName, myDF(colName).as(colName, metadata))
    }

Thanks

**Comment by JoshRosen** [comment]
To clarify:

- Which version of `spark-redshift` are you using?
- Are you trying to save a table to Redshift or read from Redshift?
- What actually happens and what do you expect to happen? Do you see an error message?

**Comment by haisano** [comment]
Hi @JoshRosen 

Thanks for the reply. 

- I use spark-redshift version 0.6.0
- I am trying to save a table to Redshift in Overwrite mode.
- I don't see any error message. But, the table is created without the column encoding that I specified.

**Comment by JoshRosen** [comment]
Support for column encodings was added in the v1.0.0 release; see the release notes at https://github.com/databricks/spark-redshift/releases/tag/v1.0.0 for more details.

**Comment by JoshRosen** [comment]
I suppose it might make sense to add "Since <version>" notes to the README in order to avoid this type of confusion. Let me file a followup ticket so I don't forget to do that...
