### ISSUE TITLE
Be able to specify s3 temp paths instead of s3n

### ISSUE THREAD

**Issue by a-morales** [databricks/spark-redshift#273]
According to the following links:
- http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-file-systems.html
- http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-file-systems.html

the block file system for s3 has had the url prefix renamed from `s3` to `s3bfs`. the `s3` prefix is now functionally interchangeable with `s3n`

**Comment by JoshRosen** [comment]
What happens if you try to do this today? Do you hit an error?

In #76 I added checking to throw an error if the S3 block filesystem is used, but this was done by actually checking whether `org.apache.hadoop.fs.s3.S3FileSystem` is being used rather than outright banning the `s3://` URI protocol: https://github.com/databricks/spark-redshift/blame/a560a2df4f23664c746279999caf3640158b09a8/src/main/scala/com/databricks/spark/redshift/Utils.scala#L161

**Comment by a-morales** [comment]
I get the error specified at https://github.com/databricks/spark-redshift/blame/a560a2df4f23664c746279999caf3640158b09a8/src/main/scala/com/databricks/spark/redshift/Utils.scala#L162 thrown. 

I've gotten around this by setting the `fs.s3.impl` in the spark context hadoop configuration to `org.apache.hadoop.fs.s3native.NativeS3FileSystem`.

**Comment by JoshRosen** [comment]
To clarify, are you actually seeing that error while running in EMR?

**Comment by a-morales** [comment]
In EMR if I don't have the hadoop configuration `fs.s3.impl` set then the error gets thrown when using the `s3` url prefix.

**Comment by jaley** [comment]
In case it helps, when I spoke to EMR support, they explained that `s3` is now just an alias to `s3n` on EMR (I don't know from which version, but certainly all the versions that package Spark). Both of them actually point to EMRFS underneath, which is strongly recommended. Using `s3a` will also work, but that will make use of the OSS S3A implementation, which is a good fast option when you're using S3 outside of EMR, but if your job is actually running on EMR, then EMRFS is generally better. We confirmed this in our testing -- performance was just as good using EMRFS, but it seemed to handle retries with S3 much better than S3A, plus it has support for S3's encryption features and consistent view, if you need those.

**Comment by JoshRosen** [comment]
My impression was that if EMRFS was being used then we'd be able to detect that by looking at the file system implementation's class; I believe that EMRFS is supposed to use `com.amazon.ws.emr.hadoop.fs.EmrFileSystem`. It seems unlikely to me that Amazon would have kept the name of the filesystem class as `org.apache.hadoop.fs.s3.S3FileSystem` while changing its implementation to be EMRFS.

**Comment by NeilJonkers** [comment]
From core-site.xml on EMR Release 5.2

fs.s3bfs.impl => org.apache.hadoop.fs.s3.S3FileSystem
fs.s3.impl      => com.amazon.ws.emr.hadoop.fs.EmrFileSystem
fs.s3n.impl    => com.amazon.ws.emr.hadoop.fs.EmrFileSystem

**Comment by JoshRosen** [comment]
@NeilJonkers, are you also seeing an error when trying to use `s3://` URIs on EMR? I wonder whether `spark-redshift` somehow isn't reflecting that configuration.

**Comment by NeilJonkers** [comment]
@JoshRosen Thank you, I experience no issue on EMR, s3:// URI is working as expected on EMR.

**Comment by JoshRosen** [comment]
@NeilJonkers, thanks for confirming. I'm going to go ahead and resolve this issue as "cannot reproduce" since I think it's no longer a problem in new versions and I haven't heard any new reports of this bug.
