### ISSUE TITLE
pyspark.sql.utils.IllegalArgumentException: u"Could not parse table name from ...'

### ISSUE THREAD

**Issue by whitish** [databricks/spark-redshift#292]
I m using:
- spark 2.0.1
- python 2.7.6
- spark-redshift_2.10:2.0.1
- RedshiftJDBC4-1.1.17.1017.jar

If I pass a regular table to `option("dbtable", "my_table")` it works good. Once I m passing a query as a _dtable_ i m receiving the error. E.g.:

```
query = "(select ....) t"
jdbcDF = sqlContext.read.format("com.databricks.spark.redshift").option("url", "jdbc:redshift://hostname:5438/dbname?user=user&password=password").option("dbtable", query).option("tempdir", 's3n://path_for_temp_data').load()
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/spark/python/pyspark/sql/readwriter.py", line 153, in load
    return self._df(self._jreader.load())
  File "/usr/local/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: u"Could not parse table name from '(select ... ) t'"
```

It works good though when I m using RedShift as a regular jdbc source:

`jdbcDF = sqlContext.read.format("jdbc").option("url", "jdbc:redshift://hostname:5438/dbname?user=user&password=password").option("dbtable", query).load()`

Here is the full command I run from shell:
`./bin/pyspark --master local --packages com.fasterxml.jackson.core:jackson-core:2.8.3,com.amazonaws:aws-java-sdk:1.11.48,org.apache.hadoop:hadoop-aws:2.6.0,com.databricks:spark-redshift_2.10:2.0.1 --exclude-packages com.fasterxml.jackson.core:jackson-annotations,com.sun.jersey:jersey-core,com.sun.jersey:jersey-json,org.codehaus.jettison:jettison,com.sun.xml.bind:jaxb-impl,javax.xml.bind:jaxb-api,javax.activation:activation,com.sun.jersey:jersey-server --driver-class-path /home/.../RedshiftJDBC4-1.1.17.1017.jar`

**Comment by JoshRosen** [comment]
Try omitting the `t` from your subquery. In other words, do 

```
query = "(select ....)"
```

instead of

```
query = "(select ....) t"
```

The problem here is that this library's table name parser expects either a valid table identifier or a string which begins and ends with parentheses, so the trailing ` t` is throwing it off. We could do a better job of throwing an error message here.

Note, also, that you can pass `.option(query, "select ...")` and omit the the parentheses in that context.

**Comment by whitish** [comment]
Thank you, @JoshRosen .
The first suggestions works as expected (after removing _t_). However, when I m trying to pass option 'query' I receive error:

```
custom_query = "select t.column1, ... from my_table t"

>>> jdbcDF = sqlContext.read.format("com.databricks.spark.redshift").option("url", "jdbc:redshift://hostoname:5438/db?user=user&password=password").option(query, custom_query).option("tempdir", 's3n://my_temp_dir').load()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/spark/python/pyspark/sql/readwriter.py", line 153, in load
    return self._df(self._jreader.load())
  File "/usr/local/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: u"You must specify a Redshift table name with the 'dbtable' parameter or a query with the 'query' parameter."
```
Any advise what I might do wrong here?

**Comment by JoshRosen** [comment]
Take a closer look at the error message:

> You must specify a Redshift table name with the 'dbtable' parameter or a query with the 'query' parameter.

You must supply _exactly one_ of these options, but this message suggests that neither option has been set properly.

It looks like you wrote

```
.option(query, custom_query)
```

Can you try using

```
.option("query", custom_query)
```

instead, with the string `"query"`?

**Comment by whitish** [comment]
Thank you.
You are right, I missed quotes around the _query_. Now this option works as expected as well.

Btw, is that possible that passing query to 'dtable' works faster than with 'query' ?

**Comment by JoshRosen** [comment]
AFAIK there shouldn't be a performance difference between `dbtable` with parentheses and `query` because both options currently get normalized to the same internal path.
