### ISSUE TITLE
Load table using custom sql

### ISSUE THREAD

**Issue by danielgallen12** [databricks/spark-redshift#293]
Hi databricks team,

Is there a way using this library to load to a redshift table by passing a custom sql statement, rather than the overwrite or append save options?

Thanks

**Comment by JoshRosen** [comment]
Not currently. Could you explain a bit more about your use-case for this?

**Comment by whitish** [comment]
@danielgallen12 , is this smth you need?
```
>>> custom_query = "(select ...)"
>>> jdbcDF = sqlContext.read.format("com.databricks.spark.redshift").option("url", "jdbc:redshift://hostname:5438/db?user=user&password=password").option("dbtable", custom_query).option("tempdir", 's3n://temp_dir').load()
```
