### ISSUE TITLE
Write encrypted temp data to S3

### ISSUE THREAD

**Issue by BogdanCojocar** [databricks/spark-redshift#297]
Hi Guys,

I'm moving some project sensible data from spark to redshift, and I don't want it to be easily readable from S3. Is there a way to encrypt the temporary data stored on S3?

Thanks,
Bogdan

**Comment by JoshRosen** [comment]
Assuming version `3.0.0-preview1` or higher of this library, check out the "Encryption" section in the README: https://github.com/databricks/spark-redshift#encryption. It documents this library's current encryption support.
