### ISSUE TITLE
Why are the schema and table name quoted?

### ISSUE THREAD

**Issue by ncanning** [databricks/spark-redshift#303]
I'm trying to write some data to Redshift, but the copy command comes out looking like
```
copy "schema"."table"
from ...
```
rather than
```
copy schema.table
from ...
```

This is reflected in the aws console as well, and no data shows up in the correct table. As far as I can tell, this is the only thing out of the ordinary here that would be cause the write to fail. Am I missing something here? This doesn't look like a bug in the code, but it seems to be causing problems.

**Comment by JoshRosen** [comment]
Quoting the table and schema name is necessary in order to allow those names to be reserved words or to contain spaces; see the documentation on "delimited identifiers" at http://docs.aws.amazon.com/redshift/latest/dg/r_names.html

**Comment by ncanning** [comment]
Ah, I see. Something else must be going wrong, then. Thanks for the quick response!
