### ISSUE TITLE
skipOnError privisioning?

### ISSUE THREAD

**Issue by apurva-sharma** [databricks/spark-redshift#307]
This is more of a question/ enhancement really.
Is there any way to skip erroneous records which fail the redshift copy?
In the current scheme, the entire job fails, when in reality one may prefer skipping erroneous records (since they are logged in the stl_error table anyway).

**Comment by JoshRosen** [comment]
Check out the `extracopyoptions` setting (documented in the README). This can be used to set options like [`MAXERROR`](http://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-load.html#copy-maxerror) during the load.

**Comment by apurva-sharma** [comment]
Thanks for the responses Josh!
