### ISSUE TITLE
Writing to parquet from redshift painfully slow

### ISSUE THREAD

**Issue by karanveerm** [databricks/spark-redshift#318]
I have a table in redshift which is about 45gb (80M rows) in size. Im trying to use this library to store it as a parquet file on S3. I'm on Spark 2.0.2 using v2.0.1 of this library: 

```
df = sqlCtx.read.format("com.databricks.spark.redshift")
      .option("url", url)
      .option("dbtable", table)
      .option("tempdir",  s"s3a://${s3Bucket}/tmp/")
      .option("jdbcdriver", "com.amazon.redshift.jdbc42.Driver")
      .load()

df.write
  .format("parquet")
  .mode(SaveMode.Overwrite)
  .save(path)
```

It takes about **1.5 hours** before I see anything at all in the spark UI. I'm running a spark cluster on EC2 with 8 cores and 30GB RAM. Once it's in the spark UI, it takes another 75 minutes for the job to finish running. 

I opened the S3 bucket to examine the contents and it seems like it took 50 minutes to even upload all the data to S3 (Im still unclear why it took 1.5 hours not 50 minutes). 

![screen shot 2017-01-10 at 5 58 20 pm](https://cloud.githubusercontent.com/assets/2851732/21832459/2318edca-d760-11e6-94de-da420c937519.png)

This seems rather slow to me. Am I doing something wrong? I can increase the size of my cluster but I don't think that is going to change the initial fixed cost. Should I need a bigger cluster for a table that is only 45gb?

Thanks in advance!

**Comment by ryantam626** [comment]
@karanveerm 
I have the same issue. I found that using a single core is faster for some reason, and I am using `com.databricks:spark-redshift_2.11:3.0.0-preview1` instead which is a bit faster as well according to my timing. (Maybe you could try to replicate this on a smaller dataset and confirm my results as well?)

And I think if you check the queries tab in Redshift, you would find the UNLOAD queries to have ran closer to 1.5 hours instead of 50 mins.

**Comment by karanveerm** [comment]
@ryantam626 I don't think I have run into the same issue as you (fewer cores for better performance).

You are right that it seems like the bottleneck is the `UNLOAD` query, not spark-redshift. We have filed an issue on the AWS discussion forms: https://forums.aws.amazon.com/thread.jspa?threadID=246927

I'm closing this issue for now since it is not a spark-redshift issue

**Comment by p5k6** [comment]
realizing this is already closed, and a bit old....figured I'd go ahead and comment in case you or others can benefit from this 😉 

If the redshift instance/spark cluster in question was in a vpc, you may need to set up an s3 endpoint within the vpc to get the proper transfer speeds. This could explain the slow run time for spark as well. At previous gig we saw a speed increase of 10-20x after adding the s3 endpoint into our vpc (From ~2-3 MB/sec to 20-30 MB/sec, iirc)
