### ISSUE TITLE
COPY multiple files to redshift 

### ISSUE THREAD

**Issue by phungleson** [databricks/spark-redshift#326]
Sorry it is not an issue but I don't know where to ask this question.

I am trying to upload the data to redshift from spark. Every time it create a very big `csv.gz` or `avro` file into s3 and COPY to redshift. It can be slow since the gz task seems to be single process.

I wonder if we can config to split that big file into smaller one so that multiple processes and upload to S3.

Thanks in advance.

**Comment by JoshRosen** [comment]
You should `repartition()` your DataFrame before saving it to Redshift.
