### ISSUE TITLE
Does redshift write support the same SaveModes as spark's dataframe writer? specifically appending to a table

### ISSUE THREAD

**Issue by tchoedak** [databricks/spark-redshift#329]
Question:
Spark's dataframe writer has the ability to pass in several options for a `SaveMode`, one being a useful `append` mode that allows you to insert a dataframe's data into a table over jdbc. From reading some of the source here, it's not immediately clear (probably because I'm unfamiliar with redshift) if `append` is supported. In some parts I see the word 'append' being used but also mentioned that spark-redshift `create`s a new table.

Sorry for my ignorance :)

**Comment by JoshRosen** [comment]
Yes, it supports append. Details of how this is implemented are described in the README at https://github.com/databricks/spark-redshift/tree/v3.0.0-preview1#guarantees-of-the-redshift-data-source-for-spark.
