### ISSUE TITLE
How can I import RedshiftInputFormat in python?

### ISSUE THREAD

**Issue by chriskinsman** [databricks/spark-redshift#33]
I can't seem to figure out the correct package name 

from com.databricks.spark.redshift import RedshiftContext fails

As does RedshiftInputFormat.  

Trying to import a file that has already been exported from Redshift using ESCAPE.

Thanks!

**Comment by marmbrus** [comment]
The only way to access this from python is through the data source API, which is only available in master.  We'll be publishing a new version of the library with this feature soon.

**Comment by mengxr** [comment]
Another way is through the `newAPIHadoopFile` method under `SparkContext` in Python. See http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.SparkContext.newAPIHadoopFile.

**Comment by JoshRosen** [comment]
It looks like the use of the data sources API from Python has been addressed by the docs in master, so I'm going to go ahead and close this ticket for now since it no longer seems actionable. Please comment if you feel that we can improve the Python documentation here.
