### ISSUE TITLE
Can't write to Redshift with Spark 1.6

### ISSUE THREAD

**Issue by proietti73** [databricks/spark-redshift#330]
Hi.
I am running the code below in a Spark 1.6 cluster (under Qubole in AWS).
But I can't get it to write data to Redshift.
Always getting the error AbstractMethodError (createRelation.. .baseRelation).
It seems a version issue... I tried many versions, including the ones below which I suppose are the righ ones.

I am very new to Spark and Databricks... so I might be missing something.
Any ideas?

Thanks,
   Benedetto

--packages "com.databricks:spark-redshift_2.10:1.1.0,org.postgresql:postgresql:9.4.1207,com.databricks:spark-avro_2.10:2.0.0"

`    val sqlc = new org.apache.spark.sql.SQLContext(sc)

    val df1 =
      sqlc
      .read
      .format("com.databricks.spark.redshift")
      .option("url", "jdbc:postgresql://........redshift.amazonaws.com:5439/prod")
      .option("user","...")
      .option("password","....")
       .option("tempdir", "s3n://..../")
      .option("query", "select aaa, bbb from sometable limit 4")
      .option("forward_spark_s3_credentials", "true")
      .load

	df1
	   .write.format("com.databricks.spark.redshift")
      .option("url", "jdbc:postgresql://........redshift.amazonaws.com:5439/prod")
      .option("user","...")
      .option("password","....")
       .option("tempdir", "s3n://..../")
       .option("dbtable", "temp_....")
       .save()
`

App > Exception in thread "main" java.lang.AbstractMethodError: com.databricks.spark.redshift.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/Dataset;)Lorg/apache/spark/sql/sources/BaseRelation;
App > at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
App > at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
App > at ProductionMetrics$.main(script.scala:104)
App > at ProductionMetrics.main(script.scala)
App > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
App > at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
App > at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
App > at java.lang.reflect.Method.invoke(Method.java:606)
App > at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:857)
App > at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:190)
App > at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:215)
App > at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:129)
App > at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
App > 17/03/02 08:52:18 Thread-2 INFO ShutdownHookManager: Shutdown hook called
App > 17/03/02 08:52:18 Thread-2 INFO ShutdownHookManager: Deleting directory /media/ephemeral0/yarn/local/usercache/bproietti/appcache/application_1488421067780_0036/spark-e613fe91-a046-4d4b-9a6d-2a9d86ad3989
App > 17/03/02 08:52:18 Asks YARN to kill this spark job INFO YarnClientImpl: Killed application application_1488421067780_0039

**Comment by proietti73** [comment]
I am able to make this work in a Spark 2 cluster. However it doesn't work in the older cluster.

**Comment by JoshRosen** [comment]
Have you double-checked the versions and made sure that you're using the versions you expect? This sounds a lot like a Spark and Redshift connector version mismatch since we've seen this exact same error when the 1.x version of this connector is used with Spark 2.x (#280) or when using the 2.x version with 1.x (#270).

For further help with this, I'd reach out to Qubole support.
