### ISSUE TITLE
java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at end of input;

### ISSUE THREAD

**Issue by mrakshay** [databricks/spark-redshift#350]
Hello I am trying to execute following query through spark-redshift:

**select 'analyze ' ||table_schema ||'.'|| table_name || ';' from information_schema.tables where table_schema = 'gis_data'**

This query works fine on Aginity Redshift.
Even its equivalent query i.e.
**select concat(concat(concat('analyze ',table_schema),concat('.',table_name)),';')
from information_schema.tables where table_schema = 'gis_data'**
also executes succcessfully.
But when I try to execute using spark jdbc, I am getting the error : 
**java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at end of input;**

How can this be resolved ??

**Comment by vickygupta0017** [comment]
what was the resolution.
