### ISSUE TITLE
DATE columns unloaded as epochmillisecs can not be loaded back into Redshift

### ISSUE THREAD

**Issue by gregrahn** [databricks/spark-redshift#39]
Both DATE and TIMESTAMP types are unloaded using epochmillisecs format currently.  Data is loaded back into Redshift by using `COPY ... TIMEFORMAT 'epochmillisecs'` [here](https://github.com/databricks/spark-redshift/blob/master/src/main/scala/com/databricks/spark/redshift/RedshiftWriter.scala#L59), however, this fails for DATE types as the default of  `DATEFORMAT 'auto'`, does not handle epochmillisecs, nor is there currently even an option of  `DATEFORMAT 'epochmillisecs'` that could be used (perhaps a good Redshift enhancement).  Given this, it seems to make more sense to use a common serialization format that could be used for both DATE and TIMESTAMP, like `YYYY-MM-DD HH:MI:SS.SSSSSS` which does work for both types even when the data contains fractional seconds using `DATEFORMAT 'YYYY-MM-DD HH:MI:SS'`.  The default format for TIMESTAMP is  `YYYY-MM-DD HH:MI:SS` so no `TIMEFORMAT` is then required. See [docs](http://docs.aws.amazon.com/redshift/latest/dg/r_DATEFORMAT_and_TIMEFORMAT_strings.html).

**Comment by JoshRosen** [comment]
I just ran into a similar issue while trying to improve this package's test coverage; some of our round-trip tests are broken because of this (this problem existed in old code but was masked by bad test assertions: #44).

**Comment by JoshRosen** [comment]
I'll try to fix this tomorrow / this weekend, but pull requests are also welcome if you want to take a stab at it.

**Comment by JoshRosen** [comment]
Alright, I think that I have a fix for this as part of #50.

**Comment by JoshRosen** [comment]
@gregrahn, I've merged #50, which should contain a fix for this issue. There might be some followup work related to timestamp precision, but I think we should file a separate issue to track any problems that arise there. Therefore, I'm going to close this as resolved but please feel free to comment / re-open if you spot any problems with my fix.
