### ISSUE TITLE
Preaction and Postaction queries should run sequentially, not in Future

### ISSUE THREAD

**Issue by meetchandan** [databricks/spark-redshift#421]
Currently, all preaction and postactions queries run as below:

```
private def executeInterruptibly[T](
      statement: PreparedStatement,
      op: PreparedStatement => T): T = {
    try {
      val future = Future[T](op(statement))(ec)
      Await.result(future, Duration.Inf)
    } catch {
      case e: InterruptedException =>
        try {
          statement.cancel()
          throw e
        } catch {
          case s: SQLException =>
            log.error("Exception occurred while cancelling query", s)
            throw e
        }
    }
  }
```

In postaction, I am trying to load a Data Frame in `temp_table`.
Run 2 update queries taking join with the `temp_table` and then dropping `temp_table`.

However, since the commands are not executed sequentially, `Drop table temp_table` gets executed immediately, and the other 2 queries fail because it doesn't find the `dropped` table anymore.

Hence, I recommend the queries in postactions to be executed sequentially.

**Comment by chandanatalef** [comment]
Figured out a solution for it.
If we run the `postactions` queries as part of a transaction. It is run sequentially.

**Comment by meetchandan** [comment]
Figured out a solution for it.
If we run the postactions queries as part of a transaction. It is run sequentially.
