### ISSUE TITLE
Basic install and usage instructions in README.md

### ISSUE THREAD

**Issue by antonycourtney** [databricks/spark-redshift#5]
Is this library packaged in some way that's easily usable from other projects?  Would be tremendously helpful if the README for this project included instructions on recommended way to use it from another sbt-based project or a pointer on where to find that information.

What I hoped might work was to just add:

```
libraryDependencies += "com.databricks.examples.redshift" %% "redshift-input-format" % "0.1"
```

to my own app's sbt project file.  Unfortunately sbt couldn't resolve the dependency when I tried that.

I will manually copy the jar from building it locally for now, but is there a better way?

Apologies for rudimentary n00b request; I'm not an sbt expert and this is my first day playing with Spark.

**Comment by bilalaslam** [comment]
:+1: on this, looks promising but not very useful without a proper README

**Comment by mengxr** [comment]
README was updated.
