### ISSUE TITLE
Port to Spark 1.3.0

### ISSUE THREAD

**Issue by antonycourtney** [databricks/spark-redshift#6]
I would very much like to use the new DataFrame work so I'm attempting to build this for Spark 1.3.0
I'll be happy to submit a Pull Request once I get it building.

Currently getting the following error:
```
[info] Compiling 2 Scala sources to /Users/antony/home/src/spark/spark-redshift/target/scala-2.10/classes...
[error] /Users/antony/home/src/spark/spark-redshift/src/main/scala/com/databricks/examples/redshift/input/RedshiftInputFormat.scala:109: value attr is not a member of String
[error]         field.name.attr.cast(field.dataType).as(Symbol(field.name))
[error]                    ^
```

The types seem to have moved around some in the change from 1.2 to 1.3.0.  It looks to me the like the type of `field.name` is String in both 1.2 and 1.3.0, so I am guessing there's some kind of implicit conversion that was visible in 1.2 that's disappeared or moved in 1.3.0.  If anyone can offer a comment on where to look to understand what `field.name.attr` was doing or suggest how to resolve, I'll do the legwork to try and fix.

**Comment by rxin** [comment]
try wrap it with col

i.e.
```scala
import org.apache.spark.sql.functions.col

col(field.name).cast(field.dataType).as(field.name)
```

**Comment by antonycourtney** [comment]
Great, thanks Reynold!  That was it.  Pull request is here:  https://github.com/databricks/spark-redshift/pull/7  
Let me know if you'd like me to make any changes to the PR.

**Comment by mengxr** [comment]
PR was merged.
