### ISSUE TITLE
`hadoop-aws` dependency

### ISSUE THREAD

**Issue by jaley** [databricks/spark-redshift#92]
We're running `spark-redshift` on EMR 4. We're trying to avoid including `org.apache.hadoop:hadoop-aws` in our build, as it conflicts with many things already provided by the EMR environment.

The assertion [here](https://github.com/databricks/spark-redshift/blob/master/src/main/scala/com/databricks/spark/redshift/Utils.scala#L112), ironically, seems to require that the `S3Filesystem` class is available on the classpath just so that we can assert that it isn't being used? We're seeing the following stacktrace on the `0.5.0` release:

```
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/s3/S3FileSystem
	at com.databricks.spark.redshift.Utils$.assertThatFileSystemIsNotS3BlockFileSystem(Utils.scala:104)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:273)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:104)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:309)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:144)
...
```

On EMR, that class shouldn't be available, as we don't want to use it. We instead use the `EmrFileSystem` class, which is provided by the environment already.

**Comment by JoshRosen** [comment]
Ah, good catch. I think that this should be pretty easy to fix by just comparing the class names.

It looks like we could have caught this by testing against Hadoop 2.6.0+ in Travis. I'll see if there's an easy way to configure that.

**Comment by JoshRosen** [comment]
@jaley, I've opened #94 to fix this. While I think that there might be testing tricks that could catch this, I don't have enough cycles to work out the all of the dependency classpath issues right now, so I'm going to submit the minimum fix to make sure this gets into the next release.
